Missing tokens
WinkFinancial/wink-assets pull request #2
Opened 2022-07-01 02:33 UTC by djaciel

- add version released to npm
- add missing tokens from namedAccounts

2022-07-01 02:58 UTC, pmprete requested changes

2022-07-01 02:58 UTC, pmprete commented on src/tokens/ethereum.ts
> +    enabled: true,
This should be disabled

2022-07-01 02:58 UTC, pmprete commented on src/tokens/ethereum.ts
> +    chainId: ChainId.Ethereum,
this should be disabled

2022-07-04 17:41 UTC, AWolfsdorf approved these changes
Nice work! I just added a question about if the added token should be disabled, if it was intended just ignore my comment

2022-07-04 17:41 UTC, AWolfsdorf commented on src/tokens/bsc.ts
> +    enabled: false,
Is ok that this token is disabled?

2022-07-12 15:40 UTC, LizanLycan approved these changes
LGTM

2022-07-12 15:57 UTC, closed without merging