Ptd 669
WinkFinancial/wink-assets pull request #27
Opened 2022-09-05 20:13 UTC by arothar

2022-09-06 02:31 UTC, pmprete requested changes
Please do not use single letter or numeric codes for reference, they become hard to read, annoying to debug and today's engine don't have performance issues when using string as keys

2022-09-06 02:31 UTC, pmprete commented on src/frecuencies.ts
> +    code: 'M',
make code human readable, like month or week or live. No need to create single letter code
```suggestion
    code: 'month',
```

2022-09-06 02:31 UTC, pmprete commented on src/usertypes.ts
> +    code: 'E',
Same as for frequency, we are trying to use human readable codes instead of single letter ones.
```suggestion
    code: 'employee',
```

2022-09-06 02:36 UTC, pmprete commented on src/currencies.ts
> +  },
I wouldn't add this now, take into account that all of the operations are un USD, so adding Pesos without the necessary refactor will be counterproductive

2022-09-08 21:44 UTC, LizanLycan approved these changes
LGTM

2022-09-09 13:24 UTC, pmprete approved these changes
Except my comment looks good

2022-09-09 13:24 UTC, pmprete commented on src/frecuencies.ts
> +    code: 'livestreaming',
just straming is ok, the concept of live streaming is from video actually, in moneay is just streaming
```suggestion
    code: 'streaming',
```

2022-09-09 16:03 UTC, merged